/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.banco.view;

import br.banco.dao.ClienteDao;
import br.banco.dao.CorrenteDao;
import br.banco.dao.PoupancaDao;
import br.banco.model.Cliente;
import br.banco.model.ContaCorrente;
import br.banco.model.ContaPoupanca;
import static br.banco.view.FrmLoginCliente.CLIENTE;
import static br.banco.view.FrmLoginCliente.CP;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diogo
 */
public class FrmDashboardCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmDashboard
     */
    static ContaPoupanca CP;
    static ContaCorrente CC;
    static Cliente CLIENTE;

    public FrmDashboardCliente() throws SQLException {
        initComponents();
        carregarDados();
        carregarLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDepositar = new javax.swing.JButton();
        btnTransferir = new javax.swing.JButton();
        labelLimiteTotal = new javax.swing.JLabel();
        labelUtilizado = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblGerente = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        lblLimiteTotal = new javax.swing.JLabel();
        lblLimiteUtilizado = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bem vindo ao BL");

        jLabel2.setText("Saldo:");

        btnDepositar.setText("Saque / Depósito");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        labelLimiteTotal.setText("Limite Total:");

        labelUtilizado.setText("Limite Utilizado:");

        jButton4.setText("Extrato");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Status:");

        jLabel7.setText("Nome:");

        jLabel8.setText("CPF:");

        jLabel9.setText("Número:");

        jLabel10.setText("Gerente:");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblNome.setText("...");

        lblCpf.setText("...");

        lblNumero.setText("...");

        lblGerente.setText("...");

        lblStatus.setText("...");

        lblSaldo.setText("...");

        lblLimiteTotal.setText("...");

        lblLimiteUtilizado.setText("...");

        labelTipo.setText("Tipo:");

        lblTipo.setText("...");

        labelData.setText("Data de Rendimento:");

        lblData.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLimiteTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLimiteTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelUtilizado)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblLimiteUtilizado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)))
                        .addGap(25, 25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(lblNome)
                    .addComponent(lblCpf)
                    .addComponent(lblNumero))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(lblGerente)
                    .addComponent(lblStatus)
                    .addComponent(lblSaldo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUtilizado)
                    .addComponent(lblLimiteTotal)
                    .addComponent(lblLimiteUtilizado)
                    .addComponent(labelData)
                    .addComponent(lblData)
                    .addComponent(labelLimiteTotal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipo)
                    .addComponent(lblTipo))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        FrmPrincipal frmPrin = new FrmPrincipal();
        frmPrin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        FrmSacar sacar = new FrmSacar();
        sacar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed
        FrmTransferencia trns = new FrmTransferencia();
        trns.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTransferirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrmExtratoCliente frmEx = null;
        try {
            frmEx = new FrmExtratoCliente();
        } catch (SQLException ex) {
            Logger.getLogger(FrmDashboardCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmEx.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed
    private void carregarLabels() {
        if (FrmLoginCliente.CP == null) {
            FrmLoginCliente.CLIENTE.getNome();
            lblNome.setText(FrmLoginCliente.CLIENTE.getNome());
            lblCpf.setText(String.valueOf(FrmLoginCliente.CLIENTE.getCpf()));
            lblNumero.setText(String.valueOf(FrmLoginCliente.CC.getNumero()));
            lblLimiteTotal.setText(String.valueOf(FrmLoginCliente.CC.getLimiteTotal()));
            lblLimiteUtilizado.setText(String.valueOf(FrmLoginCliente.CC.getLimiteUtilizado()));
            lblStatus.setText(String.valueOf(FrmLoginCliente.CC.isStatus()));
            lblTipo.setText(String.valueOf(FrmLoginCliente.CC.getTipo()));
            lblSaldo.setText(String.valueOf(CC.getSaldo()));
            lblGerente.setText(String.valueOf(FrmLoginCliente.CC.getIdGerente()));
            
            labelData.setVisible(false);
            lblData.setVisible(false);
        } else {
            FrmLoginCliente.CLIENTE.getNome();
            lblNome.setText(FrmLoginCliente.CLIENTE.getNome());
            lblCpf.setText(String.valueOf(FrmLoginCliente.CLIENTE.getCpf()));
            lblNumero.setText(String.valueOf(FrmLoginCliente.CP.getNumero()));
            lblStatus.setText(String.valueOf(FrmLoginCliente.CP.isStatus()));
            lblSaldo.setText(String.valueOf(CP.getSaldo()));
            lblData.setText(String.valueOf(FrmLoginCliente.CP.getDataRendimento()));
            lblGerente.setText(String.valueOf(FrmLoginCliente.CP.getIdGerente()));
            
            labelTipo.setVisible(false);
            lblTipo.setVisible(false);
            labelLimiteTotal.setVisible(false);
            labelUtilizado.setVisible(false);
            lblLimiteTotal.setVisible(false);
            lblLimiteUtilizado.setVisible(false);
        }
    }

    private void carregarDados() throws SQLException {
        ClienteDao cliDao = new ClienteDao();
        PoupancaDao pouDao = new PoupancaDao();
        CorrenteDao corDao = new CorrenteDao();
        CLIENTE = cliDao.selectForNomeCpf(FrmLoginCliente.CLIENTE.getNome(), FrmLoginCliente.CLIENTE.getCpf());
        CP = pouDao.selectForIdCliente(CLIENTE.getIdCLiente());
        CC = corDao.selectForIdCliente(CLIENTE.getIdCLiente());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmDashboardCliente().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmDashboardCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelLimiteTotal;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JLabel labelUtilizado;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblGerente;
    private javax.swing.JLabel lblLimiteTotal;
    private javax.swing.JLabel lblLimiteUtilizado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipo;
    // End of variables declaration//GEN-END:variables
}
